### ISSUE TITLE
New Feature: Image overlay with heatmap

### ISSUE THREAD

**Issue by iamyaash** [hexronuspi/eagleview#14]
# Heatmap
The idea is to create a feature that allows you to combine two images: an **original image** and a **heatmap**.
The heatmap is like a transparent layer that shows where the certain points of areas are more concentrated or how intense is the original image.
### Example:
![image](https://github.com/hexronuspi/eagleview/assets/84762257/8b6cd052-9bad-4abb-8bd3-cef7582dd1fd)

If this is valid, then assign me to work on this issue under **JWOC**

**Comment by hexronuspi** [comment]
this looks cool, give a link where i can read more about it.

**Comment by iamyaash** [comment]
https://www.researchgate.net/figure/Heatmap-comparison-before-and-after-adding-feature-enhancement-module-color-figure_fig10_359031386

I just got an idea of overlaying image for a new feature, then I started researching and I came across this one.

**Comment by iamyaash** [comment]
Shall I proceed, @hexronuspi?

**Comment by hexronuspi** [comment]
I still can't get where will it be used . Please explain giving examples

**Comment by iamyaash** [comment]
Just like the image shown above, we'll use it to compare two images.
However instead of comparing side-by-side, we compare it by placing original image in base and compare image on top as overlay. 
With that we can compare, the differences. Main use of this feature is just like heatmap(visually seeing the difference in original img  & heat signature img on top each other, rather than place in sides)

**Comment by hexronuspi** [comment]
Go ahead, and also add some factors like, percentage match and things like that. Also if possible add something like a segmentation such that, the overlapping image is segmented if the user asks for it specifically, this is more than a hard task so the points will be as, 
Hard = overlapping percentage or something like that
Hard x 2 = segmentation and stuff. (send 2 PR for it and open Issue, and rest i'll manage)

**Comment by hexronuspi** [comment]
updates?
 @this-is-yaash
