### ISSUE TITLE
Label Display Error

### ISSUE THREAD

**Issue by hexronuspi** [hexronuspi/eagleview#4]
Inside the file, `eagleview/figshow.py`, the class `MultiImageMatrix` is not able to print all the label corresponding to it's original `.csv`.

This prints only first row label.
```python
#v1.2
im.rand((2,4)).display_image(
    {'check_col': 'Image_Name', 'display_cols': ['Color_code', 'type'], 'display_name': True},
    {}, 
    fig_size=(20, 16),
    print_all=False,
    display_label = True,
    x=200,
    y=1600,
    fontsize=(10,10),
    text_color='white',
    label_background_color='black'
)
```

This prints first two row label.
```python
#v1.2
im.rand((2,4)).display_image(
    {'check_col': 'Image_Name', 'display_cols': ['Color_code', 'type'], 'display_name': True},
    {'check_col': 'Image_Name', 'display_cols': ['Color_code', 'type'], 'display_name': True},
    fig_size=(20, 16),
    print_all=False,
    display_label = True,
    x=200,
    y=1600,
    fontsize=(10,10),
    text_color='white',
    label_background_color='black'
)
```

Make changes such that, the display_image function here, prints all the labels corresponding to the `.csv` and it takes data in order.

**Comment by aksh1009** [comment]
I would like to work on the issue under JWOC

**Comment by aksh1009** [comment]
I would like to work on the issue under JWOC

**Comment by hexronuspi** [comment]
@aksh1009 I have assigned you the issue, proceed with it!

**Comment by hexronuspi** [comment]
@aksh1009 Progress? If you are facing any issues, write to me. If I get no response by tomorrow midnight, you will be unassigned from this issue.

**Comment by hexronuspi** [comment]
This issue is open for assignment

**Comment by iamyaash** [comment]
Assign me to this issue under **JWoC**

**Comment by this-is-yaash** [comment]
Can you please mention the time limit for each difficulty?

**Comment by hexronuspi** [comment]
This is under medium category and 2 days is the time limit.

**Comment by iamyaash** [comment]
@hexronuspi Raised a PR, please review it and let me know if there are any changes needed.
