### ISSUE TITLE
add some features

### ISSUE THREAD

**Issue by hexronuspi** [hexronuspi/eagleview#5]
currently the codebase can accept folder(s) and `.csv`(s) for image display, add some more features.

**Comment by hexronuspi** [comment]
For JWOC contributors, this issue will be given to the mentee who gives a fairly good idea.

**Comment by iamyaash** [comment]
I would like to work on that issue under JWOC
As for my idea, 
- **Copy to Clipboard**:
    Add a button or context menu option to copy the current displayed image to the clipboard for easy sharing or pasting into other applications.

**Comment by hexronuspi** [comment]
nope, that's basic. No need to add that as an extra.

**Comment by iamyaash** [comment]
how about **dark mode**
*Implement a dark mode option for users who prefer a darker color scheme during image analysis.*

**Comment by hexronuspi** [comment]
nope, as there is a color picking option for the label display as `label_background_color='black'` and text color as `text_color='white'`.

**Comment by iamyaash** [comment]
**Data Export& Reporting**
    Providing functionality to export visualized data and generate  reports in various formats in pdf or excel or some other format?

**Comment by hexronuspi** [comment]
what i meant by add some features is adding functionality to view the images in a better way like, `MultiImageMatrix` having a way to specifiy the image view for each folder seperately, or adding a method to view rgb channels per image if needed, in a special manner, check what way of displaying seems good(as they are already being displayed randomly and rgb will add more columns ).

**Comment by hexronuspi** [comment]
and after you are done with it, send a drive link with documents supporting your comment, 
the doc must have,
- sample images (MS word can be used)
- folder specification plan
   - eagleview
      - __init__.py
      - figshow.py
      - megadisplay.py # this is random
      - ... and so on
- and a output section, on how will the user output the images, example output section 
```python
from eagleview.figshow import MultiImageMatrix

im = MultiImageMatrix(
    folder_paths=['random_uploads/images', 'random_uploads/Football Dataset'],
    file_paths=['random_uploads/csv/Book1.csv', '']
)

im.rand((2,4)).display_image(
    {'check_col': 'Image_Name', 'display_cols': ['Color_code', 'type'], 'display_name': True},
    {}, # replace this with first for label displaying, this number should be the same of folder_paths number
    fig_size=(20, 16),
    print_all=False,
    display_label = True,
    x=200,
    y=1600,
    fontsize=(10,10),
    text_color='white',
    label_background_color='black'
)

```
- also add supporting texts.
,and other things can be discussed upon here itself.

**Comment by iamyaash** [comment]
assign me to work on this issue under **JWOC**

**Comment by hexronuspi** [comment]
what ideas do you have?

**Comment by hexronuspi** [comment]
It's been a day, give me updates?

**Comment by hexronuspi** [comment]
@this-is-yaash

**Comment by iamyaash** [comment]
Apologies for the late response

Implementation RGB channel view method. This feature would allow users to visualize the individual red, green, and blue channels of images within the MultiImageMatrix.

I'll start by creating a method, perhaps `display_rgb_channels`, which users can use to explore RGB channels with customizable parameters such as the color map.

**Comment by hexronuspi** [comment]
Make a new file and call figshow.py there, add that in the __init__.py and then load it kinda as pyplot does, 

Adds value then 

.show(), will plot it

**Comment by iamyaash** [comment]
## Work Logic:
To view the RGB channels of a specific image:

1. Specify the filename with extension (e.g., `filename.ext`) and store it in a variable.
2. Create an instance of `RGBView` using the specified filename:
   ```python
   from eagleview.rgbshow import RGBView
   image_filename = 'filename.ext'
   rgb_result = RGBView(image_filename)
   rgb_result.show_rgb()
   ```
![image](https://github.com/hexronuspi/eagleview/assets/84762257/e15bcbf4-5ca0-44cc-863d-97c180f89f05)

**Comment by iamyaash** [comment]
Any suggestions?
@hexronuspi

**Comment by hexronuspi** [comment]
Ya this is cool and in future I may add some other things in this file so change this name to something else which can have rgb and other things too, just think about this and let me know, also upload the .ext file, I want to see how it looks like

**Comment by iamyaash** [comment]
actually that is just a reference to the file specification.
`.ext` = `.extension`

**Comment by iamyaash** [comment]
I have created a file named **rgbshow.py**
which has the functions for rgb viewing, inside the file, I have created a class name ***RGBView***, by importing that we can use the RGB View feature.

Should I change the name for both *filename* & *class name*?

**Comment by iamyaash** [comment]
So currently we can simply execute the RGBView feature using few lines of code.
```python
from eagleview.rgbshow import RGBView
rgb_result = RGBView('random_uploads_1/images/456.jpg') #here the specified file is the filename.ext
rgb_result.show_rgb()
```

**Comment by hexronuspi** [comment]
only filename class name is good, and also make it such that the user can input multiple images from a folder as,

for one single image this rgb exists previously'

```python
from eagleview.<name> import RGBView

rgb_result = RGBView(folder = 'random_uploads_1/images') #for folder 
rgb_result.show_rgb() # shows all images
rgb_result.show_rgb(num = n).rand() # shows random 'n' images
```

**Comment by iamyaash** [comment]
Made changes to produce results with multiple images
- Upon running the program, a plot window opens, displaying an *image* alongside its *RGB channels*.
- Closing the current plot triggers the appearance of another plot with a *different image* and its *corresponding RGB channels*.
- The cycle continue until all the images in a specified directory in displayed.

**Comment by iamyaash** [comment]
@hexronuspi Submitted PR #13 
Please review it

**Comment by hexronuspi** [comment]
Give me some more time, I'm really busy these days and can not look into it. Until then, if you want to work on something else add an issue.

**Comment by iamyaash** [comment]
alright👍

**Comment by hexronuspi** [comment]
good work
