### ISSUE TITLE
minor adjustments

### ISSUE THREAD

**Issue by hexronuspi** [hexronuspi/eagleview#8]
1. The dependencies don't have compatible version ranges. It is possible some codebase is using a super old version of pandas that `eagleview` isn't compatible with, and the dependency resolver can't detect that issue automatically because the requirements let you install whichever version you want. At a minimum please find the major versions of each dependency (and combinations there of) that the code works with and specify that in the requirements.txt file. Don't get too strict in how much you narrow these down, as that will also cause resolving problems. You can use tox to help do test matrixes.

2. Update to pyproject.toml project conventions.The pyproject.toml file replaces `setup.py` and associated files in favor of a more declaritive format and given that the project doesn't need arbitrary code execution at compile time or install time it should be changed to .toml declaration.

**Comment by iamyaash** [comment]
I would like to work on that issue under JWOC

**Comment by hexronuspi** [comment]
@this-is-yaash  proceed

**Comment by iamyaash** [comment]
May I know the **time limit** for this issue?

**Comment by hexronuspi** [comment]
I don't quite remember but it was 1 day for an easy task. So, tomorrow if
there is no update from the present mentee it'll be passed to the mentee
next in line.

**Comment by iamyaash** [comment]
```bash
[thisisyaash@yaash eagleview]$ git push -u origin minor-adjustments-branch 
remote: Permission to hexronuspi/eagleview.git denied to this-is-yaash.
fatal: unable to access 'https://github.com/hexronuspi/eagleview.git/': The requested URL returned error: 403
```
I need assistance for commiting changes to this repo

**Comment by hexronuspi** [comment]
make appriopriate changes to your forked repository and then make a pull request to the branch named as `toml-specific`

**Comment by iamyaash** [comment]
I've submitted a *PR*. Could you please review it and let me know if there are any changes needed? Thanks!

**Comment by hexronuspi** [comment]
@this-is-yaash  Done
